Import('env')

appEnv = env.Clone()

appEnv.Append(CPPPATH = [
    '#src/app/',
    ])

demo = appEnv.Program(
    target = 'demo',
    source = [
        'main.c',
        ],
    LIBS = ['stelaris','driver']
    )
    
appEnv.Install('#bin/',appEnv.Objcopy(demo))

